version: '2.1'
services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db/KtorEasyDBSnap:/var/lib/mysql
      - ./db/dbConfig:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=ktoreasydb
      - MYSQL_USER=ktoreasyuser
      - MYSQL_PASSWORD=ktoreasypassword
    ports:
      - "3308:3306"

  backend:
    image: ktoreasy:latest
    mem_limit: 300m
    depends_on:
      - db
    environment:
      - ENVIRONMENT=dev
    restart: always
    ports:
      - "3510:3500"

  dbBackup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    restart: always
    volumes:
      - ./db/KtorEasyDBSnap:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=mypassword
      - MYSQL_DB=ktoreasydb
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1